import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import './styles.css';

const productUrl = 'https://patienceai.in';
const heroLines = ['AI with clear boundaries.', 'A Linux foundation for useful work.', 'Your intent stays in charge.', 'Local-first. Quietly capable.'];
const consentVersion = '2026-09-10-v1';
const seoPages = {
  '/': ['Fabric OS — by Patience AI', 'A calmer Linux foundation for intelligent work.'],
  '/architecture': ['Fabric OS architecture — Patience AI', 'The public Fabric OS model: intent, boundaries, outcomes, and recovery.'],
  '/security': ['Fabric OS security — Patience AI', 'Security principles for a local-first Linux foundation with clear boundaries.'],
  '/download': ['Download Fabric OS — Patience AI', 'Evaluate the early Fabric OS build on a dedicated x86_64 UEFI device.'],
  '/docs': ['Fabric OS documentation — Patience AI', 'Public product, device, Linux, security, privacy, and license documentation.'],
  '/device': ['Fabric OS device guide — Patience AI', 'A practical real-device validation checklist for the early Fabric OS build.'],
  '/privacy': ['Fabric OS privacy — Patience AI', 'Privacy choices and public data-handling principles for Fabric OS.'],
  '/terms': ['Fabric OS terms — Patience AI', 'Terms for the Fabric OS research release.'],
  '/licenses': ['Fabric OS licenses — Patience AI', 'Open-source license and attribution guidance for Fabric OS.'],
  '/compliance': ['Fabric OS compliance — Patience AI', 'Public launch-readiness principles for the website and Linux-based OS.'],
};

function Logo() {
  return <Link className="logo" to="/"><span className="logo-mark"><i /><i /><i /></span><span className="logo-type"><span>fabric<span className="logo-muted">OS</span></span><small>by patience AI</small></span></Link>;
}

function RotatingLine() { const [index, setIndex] = useState(0); useEffect(() => { const timer = setInterval(() => setIndex((value) => (value + 1) % heroLines.length), 3600); return () => clearInterval(timer); }, []); return <span className="sentence-change" key={index}>{heroLines[index]}</span>; }

function Seo() {
  const location = useLocation();
  useEffect(() => {
    const [title, description] = seoPages[location.pathname] || seoPages['/'];
    document.title = title;
    const descriptionTag = document.querySelector('meta[name="description"]');
    if (descriptionTag) descriptionTag.setAttribute('content', description);
    const canonical = document.querySelector('link[rel="canonical"]');
    if (canonical) canonical.setAttribute('href', `https://fabricos.patienceai.in${location.pathname === '/' ? '/' : location.pathname}`);
  }, [location.pathname]);
  return null;
}

function Header() {
  const location = useLocation();
  return <header className="site-header"><Logo /><nav className="nav-links">
    <NavLink className={({ isActive }) => isActive ? 'active' : ''} to="/architecture">Architecture</NavLink>
    <NavLink className={({ isActive }) => isActive ? 'active' : ''} to="/security">Security</NavLink>
    <NavLink className={({ isActive }) => isActive ? 'active' : ''} to="/download">Download</NavLink>
  </nav><div className="header-actions"><Link className="button button-small button-dark" to="/download">Get Fabric OS <span>↗</span></Link></div><button className="mobile-menu" aria-label="Menu">☰</button></header>;
}

function getConsent() { try { const match = document.cookie.match(/(?:^|; )fabric_consent=([^;]+)/); return match ? JSON.parse(decodeURIComponent(match[1])) : null; } catch { return null; } }
function saveConsent(preferences) { const value = { ...preferences, version: consentVersion }; const secure = window.location.protocol === 'https:' ? '; Secure' : ''; document.cookie = `fabric_consent=${encodeURIComponent(JSON.stringify(value))}; Max-Age=31536000; Path=/; SameSite=Lax${secure}`; fetch('/api/consent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ policyVersion: consentVersion, preferences }) }).catch(() => {}); return value; }
function CookieConsent() { const [visible, setVisible] = useState(false); const [open, setOpen] = useState(false); const [analytics, setAnalytics] = useState(false); useEffect(() => { const stored = getConsent(); if (stored) setAnalytics(Boolean(stored.analytics)); else setVisible(true); }, []); const commit = (allowAnalytics) => { setAnalytics(allowAnalytics); saveConsent({ necessary: true, analytics: allowAnalytics }); setVisible(false); setOpen(false); }; return <div className="consent-layer">{visible && <section className={`consent-panel ${open ? 'consent-expanded' : ''}`} role="dialog" aria-modal="false" aria-labelledby="consent-title"><div className="consent-head"><div><span className="consent-kicker">Privacy choices</span><h2 id="consent-title">Your data, your say.</h2></div><button className="consent-close" onClick={() => setVisible(false)} aria-label="Close privacy choices">×</button></div><p>Necessary storage remembers this choice. Optional analytics is off unless you choose it.</p>{open && <div className="consent-options"><label><span><b>Necessary</b><small>Required for preferences and security.</small></span><input type="checkbox" checked disabled /></label><label><span><b>Analytics</b><small>Anonymous release and site-use measurement.</small></span><input type="checkbox" checked={analytics} onChange={(event) => setAnalytics(event.target.checked)} /></label></div>}<div className="consent-actions"><button className="button button-quiet" onClick={() => commit(false)}>Decline optional</button><button className="button button-quiet" onClick={() => setOpen((value) => !value)}>{open ? 'Hide choices' : 'Manage choices'}</button><button className="button button-dark" onClick={() => commit(open ? analytics : true)}>Accept optional</button></div><Link className="consent-policy" to="/privacy">Read the privacy notice →</Link></section>}{!visible && <button className="consent-manage" onClick={() => { setVisible(true); setOpen(true); }}>Privacy settings</button>}</div>; }

function Footer() {
  return <footer className="footer"><div><Logo /><p className="footer-note">A thoughtful foundation for the next<br />generation of computing.</p></div><div className="footer-links"><div><span>Explore</span><Link to="/architecture">Architecture</Link><Link to="/security">Security</Link><Link to="/download">Download</Link></div><div><span>Resources</span><a href="/docs/fabric-os-guidebook.pdf" target="_blank" rel="noreferrer">Documentation</a><a href={productUrl} target="_blank" rel="noreferrer">Patience AI</a><a href="mailto:info@patienceai.in">info@patienceai.in</a></div><div><span>Legal</span><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/licenses">Licenses</Link><Link to="/compliance">Compliance</Link></div></div><div className="copyright">© 2026 Patience AI<br />All copyright reserved.</div></footer>;
}

function Orb({ small = false }) { return <div className={`orb-wrap ${small ? 'orb-small' : ''}`}><div className="orb-glow" /><div className="orb"><span className="orb-line line-one" /><span className="orb-line line-two" /><span className="orb-line line-three" /><span className="orb-core" /></div><div className="orb-shadow" /></div>; }

function FabricMotion() {
  const canvasRef = useRef(null);
  useEffect(() => {
    const canvas = canvasRef.current;
    const context = canvas.getContext('2d');
    let frameId;
    let active = false;
    let pointerX = 0;
    let pointerY = 0;
    const particles = Array.from({ length: 72 }, (_, index) => ({ angle: index * 2.399, radius: 0.2 + ((index * 17) % 80) / 100, depth: ((index * 29) % 100) / 100, size: 0.7 + (index % 3) * .35 }));
    const resize = () => { const ratio = window.devicePixelRatio || 1; canvas.width = canvas.clientWidth * ratio; canvas.height = canvas.clientHeight * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); };
    const move = (event) => { const rect = canvas.getBoundingClientRect(); pointerX = (event.clientX - rect.left) / rect.width - .5; pointerY = (event.clientY - rect.top) / rect.height - .5; };
    const enter = () => { active = true; };
    const leave = () => { active = false; pointerX = 0; pointerY = 0; };
    const draw = (now) => {
      const width = canvas.clientWidth; const height = canvas.clientHeight; const cx = width / 2; const cy = height / 2; const scale = Math.min(width, height); const speed = active ? 1.7 : .65; const time = now * .001 * speed;
      context.clearRect(0, 0, width, height);
      const wash = context.createRadialGradient(cx - scale * .08, cy - scale * .12, 0, cx, cy, scale * .5); wash.addColorStop(0, 'rgba(223,255,98,.8)'); wash.addColorStop(.18, 'rgba(111,133,255,.48)'); wash.addColorStop(1, 'rgba(38,45,150,0)'); context.fillStyle = wash; context.fillRect(0, 0, width, height);
      context.save(); context.translate(cx, cy); context.rotate(pointerX * .08 + Math.sin(time * .32) * .04); context.scale(1 + pointerY * -.03, 1 + pointerX * .03);
      for (let ring = 0; ring < 4; ring += 1) { context.beginPath(); context.ellipse(0, 0, scale * (.22 + ring * .055), scale * (.08 + ring * .024), time * (.16 + ring * .04) + ring * 1.4, 0, Math.PI * 2); context.strokeStyle = `rgba(${ring === 2 ? '223,255,98' : '189,209,255'},${.32 - ring * .045})`; context.lineWidth = 1; context.stroke(); }
      particles.forEach((particle) => { const angle = particle.angle + time * (.15 + particle.depth * .18); const orbit = scale * (.16 + particle.radius * .18); const x = Math.cos(angle) * orbit; const y = Math.sin(angle) * orbit * (.37 + particle.depth * .25); const z = (Math.cos(angle) + 1) / 2; const glow = context.createRadialGradient(x, y, 0, x, y, particle.size * 5); glow.addColorStop(0, z > .5 ? 'rgba(223,255,98,.95)' : 'rgba(167,190,255,.85)'); glow.addColorStop(1, 'rgba(90,110,255,0)'); context.fillStyle = glow; context.beginPath(); context.arc(x, y, particle.size * 5, 0, Math.PI * 2); context.fill(); });
      context.restore(); frameId = requestAnimationFrame(draw);
    };
    resize(); window.addEventListener('resize', resize); canvas.addEventListener('pointermove', move); canvas.addEventListener('pointerenter', enter); canvas.addEventListener('pointerleave', leave); frameId = requestAnimationFrame(draw);
    return () => { cancelAnimationFrame(frameId); window.removeEventListener('resize', resize); canvas.removeEventListener('pointermove', move); canvas.removeEventListener('pointerenter', enter); canvas.removeEventListener('pointerleave', leave); };
  }, []);
  return <canvas ref={canvasRef} className="fabric-motion" aria-label="Original animated AI system visualization" />;
}

function FabricScene() { return <div className="scene" aria-label="Animated 3D Fabric OS system core"><div className="scene-haze" /><FabricMotion /><div className="scene-ring ring-a" /><div className="scene-ring ring-b" /><div className="scene-ring ring-c" /><div className="scene-cube"><span /><span /><span /><span /><span /><span /></div><div className="scene-node node-a">01</div><div className="scene-node node-b">AI</div><div className="scene-node node-c">↗</div><div className="scene-shadow" /></div>; }

const pillars = [
  ['01', 'Intent first', 'Work begins with what you mean.'],
  ['02', 'Policy before power', 'Every capability is scoped, revocable, and checked before anything runs.'],
  ['03', 'Reversible by design', 'Transactions, provenance, and rollback make important actions understandable and recoverable.']
];

function Home() {
  return <><main className="home"><section className="hero section-shell"><div className="hero-copy"><h1>A calmer<br /><em>operating system</em><br />for intelligent work.</h1><p className="lede"><RotatingLine /></p><div className="hero-actions"><Link className="button button-dark" to="/download">Explore the build <span>↗</span></Link><Link className="button button-quiet" to="/architecture">See how it works <span>↓</span></Link></div><div className="hero-meta"><span><b className="status-dot" />Local-first</span><span><b />Open architecture</span><span><b />Built on Linux</span></div></div><div className="hero-art"><div className="art-label label-top">AI / LINUX / HUMAN</div><FabricScene /><div className="art-label label-bottom"><span>FABRIC-01</span><span>● LIVE SYSTEM</span></div></div></section><section className="marquee"><div>INTENT <span>✳</span> POLICY <span>✳</span> PROVENANCE <span>✳</span> ROLLBACK <span>✳</span> INTENT <span>✳</span> POLICY <span>✳</span> PROVENANCE <span>✳</span> ROLLBACK <span>✳</span></div></section><section className="section-shell intro-grid"><div><div className="eyebrow">01 / The idea</div><h2>Software that<br /><em>knows its place.</em></h2></div><div className="intro-right"><p className="big-copy">AI can help without taking over. Fabric OS keeps the boundary clear between a suggestion and an action.</p><Link className="arrow-link" to="/architecture">Meet the architecture <span>→</span></Link></div></section><section className="section-shell pillars"><div className="section-kicker">THE FABRIC PRINCIPLES</div>{pillars.map(([num, title, copy]) => <article className="pillar" key={num}><span className="pillar-num">{num}</span><div><h3>{title}</h3><p>{copy}</p></div><span className="pillar-arrow">↗</span></article>)}</section><section className="section-shell cta-band"><div><div className="eyebrow">Early build</div><h2>Make room for<br /><em>better work.</em></h2></div><div><p>Try a safe, bootable foundation for your own experiments.</p><Link className="button button-dark" to="/download">Download Fabric OS <span>↗</span></Link></div></section></main><Footer /></>;
}

function Architecture() { return <PageLayout eyebrow="02 / Architecture" title={<>From intent<br /><em>to outcome.</em></>} intro="A public view of the Fabric OS approach: clear intent, careful boundaries, and work you can understand."><section className="process-grid">{[['01', 'Intent', 'Start with what you want to do.'], ['02', 'Assistance', 'AI helps shape the next step.'], ['03', 'Boundaries', 'The system keeps access limited and clear.'], ['04', 'Outcome', 'Work happens only within those limits.'], ['05', 'Recovery', 'Important changes stay reviewable and reversible.']].map(([num, title, copy], index) => <article className="process-card" key={num}><span>{num}</span><div className="process-icon">{index === 0 ? '✦' : index === 1 ? '◌' : index === 2 ? '⊙' : index === 3 ? '↗' : '⌁'}</div><h3>{title}</h3><p>{copy}</p></article>)}</section><section className="public-diagram"><div className="diagram-caption"><span className="eyebrow">A simple way to think about it</span><p>Fabric OS keeps the important parts visible.</p></div><div className="diagram-flow"><div className="diagram-step"><span className="diagram-number">01</span><div className="diagram-orb orb-intent">✦</div><h3>Intent</h3><p>What you want to happen.</p></div><div className="diagram-connector"><i /><i /><i /></div><div className="diagram-step"><span className="diagram-number">02</span><div className="diagram-orb orb-boundary">◌</div><h3>Boundaries</h3><p>What is allowed to happen.</p></div><div className="diagram-connector"><i /><i /><i /></div><div className="diagram-step"><span className="diagram-number">03</span><div className="diagram-orb orb-outcome">↗</div><h3>Outcome</h3><p>What you can review and keep.</p></div></div></section><section className="how-it-works"><div><span className="eyebrow">How it works</span><h2>Simple on the<br /><em>surface.</em></h2></div><div className="how-steps">{[['01', 'Say what you need', 'Start with a goal in your own words.'], ['02', 'See the next step', 'Fabric OS turns that goal into a clear, bounded suggestion.'], ['03', 'Stay in control', 'You can accept, change, or stop before important work begins.'], ['04', 'Keep the result', 'The work stays understandable, and important changes can be reviewed or undone.']].map(([num, title, copy]) => <article key={num}><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section><section className="statement"><div className="statement-orb"><Orb small /></div><div><div className="eyebrow">The public principle</div><blockquote>“AI helps. People decide.”</blockquote><p>Fabric OS keeps the product simple to explain: useful assistance, explicit limits, and no hidden promise of autonomy.</p></div></section></PageLayout>; }

function Security() { return <PageLayout eyebrow="03 / Security" title={<>Quietly<br /><em>defensible.</em></>} intro="The simple promise: useful AI, clear limits, and a system that fails safely."><section className="security-layout"><div className="security-list">{[['Fail closed', 'No approval means no access.'], ['Scoped capabilities', 'Each task gets only what it needs.'], ['Private by default', 'Local-first use keeps sensitive work close.'], ['Auditable actions', 'Important changes remain understandable and reversible.']].map(([title, copy], i) => <article key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{copy}</p></div><b>↗</b></article>)}</div><div className="security-panel"><div className="panel-top"><span>FABRIC GUARD</span><span>ONLINE</span></div><div className="shield">◇<div className="shield-ring" /></div><h3>Human intent<br /><em>remains the boundary.</em></h3><div className="panel-bottom"><span>PUBLIC PRINCIPLES</span><span className="green-dot" />READY</div></div></section><section className="quote-band"><p>“Trust is built by showing the boundary.”</p></section></PageLayout>; }

function Download() { return <PageLayout eyebrow="04 / Download" title={<>Your next<br /><em>system, ready.</em></>} intro="The early Fabric OS build is for dedicated x86_64 UEFI device validation. The image is still under development and is not published yet."><section className="download-panel"><div className="download-main"><div className="release-badge"><span className="status-dot" />Early access · build 0.1.0</div><h2>Fabric OS<br /><em>foundation image</em></h2><p>A bootable Linux-compatible image for careful device testing and research.</p><div className="download-row"><button className="button button-dark" type="button" disabled>Image coming soon</button><span className="checksum">Ext4 image<br /><b>Not published</b></span></div></div><div className="support-card"><div className="card-title">Supported environments</div><div className="support-item"><span className="platform-icon">⌘</span><div><b>x86_64 / UEFI</b><small>Validation target</small></div><i>✓</i></div><div className="support-item"><span className="platform-icon">▣</span><div><b>Dedicated test device</b><small>Required for install</small></div><i>✓</i></div><div className="support-item muted"><span className="platform-icon">◈</span><div><b>ARM64</b><small>Planned · coming soon</small></div><i>—</i></div><div className="support-item muted"><span className="platform-icon">▥</span><div><b>Daily-use machines</b><small>Not recommended yet</small></div><i>—</i></div></div></section><section className="download-note"><span>Before you install</span><p>When the image is published, use a spare machine, verify the checksum, back up the disk, and follow the device validation guide.</p><Link to="/device">Open device guide →</Link></section></PageLayout>; }

function DeviceGuide() { return <PageLayout eyebrow="10 / Device guide" title={<>Test it<br /><em>in the real world.</em></>} intro="A practical checklist for evaluating Fabric OS on a dedicated x86_64 UEFI machine. Do not use your only computer."><section className="device-steps">{[['01', 'Prepare', 'Choose a spare device. Record its model, CPU, memory, graphics, storage, Wi-Fi, and firmware settings. Back up anything you cannot replace.'], ['02', 'Verify', 'Download the exact release, compare its published SHA-256 value, and keep the release notes with the device record.'], ['03', 'Install carefully', 'Use a dedicated disk or test machine. Confirm the target disk before writing and keep a recovery path available.'], ['04', 'Check the basics', 'Test boot, display, keyboard, touchpad, storage, network, audio, sleep, restart, shutdown, and clock behavior.'], ['05', 'Check the promise', 'Try local-only use, provider off mode, permissions, blocked actions, rollback, and data removal with non-sensitive test data.'], ['06', 'Record the result', 'Save the device model, release hash, steps taken, failures, logs without secrets, and whether the device is safe to use again.']].map(([num, title, copy]) => <article key={num}><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</section><section className="device-warning"><b>Important</b><p>The current artifact is an early research image, not a universal installer. Device readiness is not claimed until the exact hardware, install path, recovery path, and release artifact have been tested and approved.</p></section></PageLayout>; }

function PageLayout({ eyebrow, title, intro, children }) { return <><main className="inner-page section-shell"><div className="page-heading"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lede">{intro}</p></div>{children}</main><Footer /></>; }

function trackDownload(platform) { fetch('/api/downloads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ platform }) }).catch(() => {}); }

function LegalPage({ eyebrow, title, intro, children }) { return <PageLayout eyebrow={eyebrow} title={title} intro={intro}><article className="legal-copy">{children}<p className="legal-disclaimer">These materials are a product-launch starting point, not legal advice. Patience AI should have counsel review and complete the marked entity, jurisdiction, vendor, retention, and transfer details before launch.</p></article></PageLayout>; }

function Privacy() { return <LegalPage eyebrow="05 / Privacy" title={<>Privacy,<br /><em>in plain language.</em></>} intro="This notice covers the Fabric OS website and the privacy choices planned for the OS."><h2>Who is responsible</h2><p><strong>Patience AI</strong> is the intended data controller for the website and any OS service that Patience AI operates. The legal entity name, registered address, supervisory authority, and representative details must be completed before launch. For questions or rights requests, email <a href="mailto:info@patienceai.in">info@patienceai.in</a>.</p><h2>What we collect</h2><p>The public download form records the selected platform and request time. The OS is designed to keep intent, credentials, AI memory, diagnostics, and provider traffic under explicit user controls. It must not collect names, API keys, prompts, files, or model content for release analytics. Hosting, CDN, update, and security infrastructure may create technical logs; each provider and retention period must be documented before launch.</p><h2>Consent choices</h2><p>Necessary preference storage is used to remember your privacy choice. Optional analytics is off by default and activates only after you choose it. You can withdraw or change the choice at any time with the Privacy Settings control. The same clear, granular, and reversible approach is intended for any consent screen in the OS.</p><h2>Why we use it</h2><p>Data is used only for a stated product, support, security, or release purpose. Each OS and website flow needs a recorded lawful basis, retention period, access owner, and deletion path before production use.</p><h2>Your rights</h2><p>Subject to applicable law, you may ask for access, correction, deletion, restriction, objection, portability, or information about processing. Send a request to <a href="mailto:info@patienceai.in">info@patienceai.in</a>. We may need to verify identity and will respond within the applicable legal deadline.</p><h2>Cookies and transfers</h2><p>The site does not use advertising cookies. The OS is local-first; cloud AI, updates, support, and diagnostics must show their network and privacy implications. Any transfer outside the EEA needs a documented transfer mechanism and vendor assessment.</p></LegalPage>; }

function Terms() { return <LegalPage eyebrow="06 / Terms" title={<>Clear terms<br /><em>for an early build.</em></>} intro="Fabric OS is research software. These terms explain the limited permission to use it and the responsibilities that come with an early release."><h2>Research release</h2><p>Fabric OS is provided for evaluation, research, and development. It may be incomplete, change without notice, or contain defects. Do not use it as the sole system for safety-critical, regulated, or production workloads.</p><h2>License</h2><p>The repository is released under the Apache License 2.0 unless a file or dependency states otherwise. The license grants the permissions and imposes the conditions described in the included license text and notices.</p><h2>Your responsibility</h2><p>Use a virtual machine first, protect your data, review downloaded artifacts, and comply with the laws and third-party terms that apply to your use. Do not use Fabric OS to access data or systems without authorization.</p><h2>Warranty and liability</h2><p>To the extent permitted by law, the software and website are provided without warranties. Nothing here limits rights or remedies that cannot legally be excluded. The final contracting entity, governing law, venue, export-control position, and consumer terms must be completed by counsel before launch.</p></LegalPage>; }

function Licenses() { return <LegalPage eyebrow="07 / Licenses" title={<>Open by<br /><em>default.</em></>} intro="Fabric OS is built to be inspected, adapted, and improved. Keep the license and attribution notices with the parts you redistribute."><h2>Fabric OS</h2><p>The repository is available under the <strong>Apache License 2.0</strong>. The full license text is included in the repository at <code>LICENSE</code>.</p><h2>Website dependencies</h2><p>The public website uses React, React DOM, React Router, Vite, Express, node-postgres, and the Vite React plugin. These dependencies are distributed under their own MIT licenses. The complete attribution list is included in <code>website/THIRD-PARTY-NOTICES.md</code>.</p><h2>Third-party content</h2><p>The website’s visual mark and motion system are original project assets. Do not assume that external fonts, icons, models, data, or downloaded packages are covered by the Fabric OS license. Review and record each asset’s provenance before shipping.</p></LegalPage>; }

function Compliance() { return <LegalPage eyebrow="08 / Compliance" title={<>Launch<br /><em>with care.</em></>} intro="A public view of the work required across the website and the Linux-based Fabric OS."><div className="compliance-grid">{[['Privacy', 'Controller identity, notices, lawful bases, rights, retention, vendors, and transfers.'], ['Security', 'Threat model, secure updates, credentials, incident response, and vulnerability handling.'], ['Software supply chain', 'SBOM, licenses, signed artifacts, checksums, provenance, and reproducible-build goals.'], ['OS release', 'Supported hardware, QEMU testing, recovery, rollback, accessibility, and clear limitations.']].map(([title, copy]) => <div className="compliance-card" key={title}><span>◉</span><h3>{title}</h3><p>{copy}</p></div>)}</div><h2>Before launch</h2><p>Complete the legal entity and address, appoint the privacy contact or DPO where required, approve the record of processing, sign processor agreements, configure retention and deletion, test rights requests, run a risk assessment/DPIA where required, verify the OS release gates, publish the final policies, and have counsel sign off on market-specific obligations.</p></LegalPage>; }

function Docs() { return <PageLayout eyebrow="09 / Documentation" title={<>The public<br /><em>guide.</em></>} intro="Start here for the product story, device evaluation, and release boundaries."><section className="docs-grid">{[['What it is', 'A Linux-compatible, local-first foundation for AI-assisted work.'], ['How to evaluate', 'Use a dedicated device, verify the release, and keep a recovery path.'], ['What matters', 'Human intent, clear limits, provenance, and recovery.'], ['Before launch', 'Review security, privacy, licenses, supply chain, and support gates.']].map(([title, copy]) => <article className="docs-card" key={title}><span>↗</span><h3>{title}</h3><p>{copy}</p></article>)}</section><div className="docs-cta"><a className="button button-dark" href="/docs/fabric-os-guidebook.pdf" target="_blank" rel="noreferrer">Open Fabric OS Guidebook <span>↗</span></a><span>Product, Linux, security, privacy, and license basics.</span></div><section className="launch-facts"><div><b>Device validation</b><span>Real hardware</span></div><div><b>x86_64 / UEFI</b><span>Initial target</span></div><div><b>Apache 2.0</b><span>Open license</span></div><div><b>Local-first</b><span>Cloud optional</span></div></section><section className="docs-links"><span>Public references</span><Link to="/architecture">Product principles →</Link><Link to="/device">Device guide →</Link><Link to="/security">Security →</Link><Link to="/compliance">Launch compliance →</Link></section></PageLayout>; }

function App() { return <><Seo /><Header /><Routes><Route path="/" element={<Home />} /><Route path="/architecture" element={<Architecture />} /><Route path="/security" element={<Security />} /><Route path="/download" element={<Download />} /><Route path="/docs" element={<Docs />} /><Route path="/device" element={<DeviceGuide />} /><Route path="/privacy" element={<Privacy />} /><Route path="/terms" element={<Terms />} /><Route path="/licenses" element={<Licenses />} /><Route path="/compliance" element={<Compliance />} /></Routes><CookieConsent /></>; }

createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>);
